# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  updateServer:
    # needs: check
    # if: needs.check.outputs.run_job == 'true'
    runs-on: self-hosted
    steps:
      - name: Updating server
        uses: actions/checkout@v2
      # - run: echo "This job runs only when modified files are under the 'server' folder."
      - run: npm --prefix ./server install
      - run: pm2 reload trailseek --update-env

  # check:
  #   name: Checking changed files
  #   outputs:
  #     run_job: ${{ steps.check_files.outputs.run_job }}
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 2

  #     - name: Check modified files
  #       id: check_files
  #       run: |
  #         echo "========== check paths of modified files =========="
  #         files=$(git diff --name-only HEAD^ HEAD)
  #         echo $files
  #         if [[ $files == "server/"* ]]; then
  #           echo "::set-output name=run_job::true"
  #         else
  #           echo "No modification for server deployment"
  #         fi
