# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches:
      - master
    paths:
      - 'Recommendation/**'
      - 'server/**'

jobs:
  serverUpdate:
    runs-on: self-hosted
    steps:
      - name: Updating server
        uses: actions/checkout@v2
      - run: echo "This job runs only when modified files are under the 'server' folder."
      - run: npm --prefix ./server install
      - run: npm --prefix ./server run test
      - run: pipenv run pip install -r <(pipenv lock -r) --target ./Recommendation/
      - run: pm2 reload trailseek --update-env
